#include <sys/wait.h>
#include <string.h>
#include <unistd.h>

void merge_quotes(char *arg[]){
   /**
    * merge_quotes: function checks and merges single quotations into one array
    *
    * Parameters:
    * arg - pointer to a command line argument which will be checked for single quotes
    *
    */
   
     for(int i = 0; i < 9; i++){
      if(arg[i] == NULL || arg[i + 1] == NULL){
         break;
      }

        if(strcmp(arg[i],"'") == 0 && strcmp(arg[i+1],"'") == 0){
         strcat(arg[i], " "); 
         strcat(arg[i],arg[i+1]);
          arg[i+1] = NULL;

          for(int j = i + 1; j  < 8; j++){
            arg[j] = arg[j+1];
          }
          arg[9] = NULL;
         }
 
      }
   }



int read_input(char *arg1[], char *arg2[], char *arg3[], char *arg4[])
{
   /**
    * read_input
    *
    * Parameters:
    * arg1 - pointer to 1st command line arguement
    * arg2 - pointer 2nds command line arguement
    * arg3 - pointer to 3rd command line argument
    * arg4 - pointer 4th command line argument
    *
    * Returns
    * argc - the number of arguments entered
    */
   char arg[4][256];
   char *args[10];
   int argc = 0;

   ssize_t read_file;

   /* Used for user input */

   for (int i = 0; i < 4; i++) /* Line 58 - 71: Uses code that is generated from ChatGPT */
   {
      read_file = read(0, arg[i], sizeof(arg[i]) - 1);

      arg[i][read_file] = '\0';

      if (strcmp(arg[i], "\n") == 0)
      {
         break;
      }

      arg[i][strcspn(arg[i], "\n")] = '\0';
      argc++;
   }
   
   /* Following code seperates each word in arrays by spaces */
   char *token = strtok(arg[0], " ");
   int temp = 0;
   while (token != NULL && temp < 9)
   {
      arg1[temp++] = token;
      token = strtok(NULL, " ");
   }
   arg1[temp] = NULL;

   temp = 0;
   token = strtok(arg[1], " ");
   while (token != NULL && temp < 9)
   {
      arg2[temp++] = token;
      token = strtok(NULL, " ");
   }
   arg2[temp] = NULL;

   temp = 0;
   token = strtok(arg[2], " ");
   while (token != NULL && temp < 9)
   {
      arg3[temp++] = token;
      token = strtok(NULL, " ");
   }
   arg3[temp] = NULL;

   temp = 0;
   char temp2[256];
   token = strtok(arg[3], " ");
   while (token != NULL && temp < 9)
   {
      arg4[temp++] = token;
      token = strtok(NULL, " ");
   }
   arg4[temp] = NULL;
   return argc;
}

int main()
{
   int fds[2], fds2[2], fds3[2]; /* Holds file descriptors */
   char *argv1[10] = {NULL}; /* Line 115 - 118: Holds user input */
   char *argv2[10] = {NULL};
   char *argv3[10] ={NULL};
   char *argv4[10] = {NULL};

   int argc = read_input(argv1, argv2, argv3, argv4); /* Returns number of arguments and initializes argv1 to argv4 */
   if (argc == 0)
   {
      return 0;
   }

   merge_quotes(argv1); /* Code merges any empty single quotes here */
   merge_quotes(argv2);
   merge_quotes(argv3);
   merge_quotes(argv4);
 
   pipe(fds);
   pipe(fds2);
   pipe(fds3);

   pid_t pid1, pid2, pid3, pid4; /* pid numbers */

   if ((pid1 = fork()) == 0)
   {
      if (argc == 1)
      {
         dup2(fds[0], STDIN_FILENO); /* Reads input and puts data into file descriptor */
      }
      else
      {
         dup2(fds[1], STDOUT_FILENO);
      }

      close(fds[0]);
      close(fds[1]);
      close(fds2[0]);
      close(fds2[1]);
      close(fds3[0]);
      close(fds3[1]);

      if (execvp(argv1[0], argv1) < 0)
      return -1;
   }

   if ((pid2 = fork()) == 0)
   {
      dup2(fds[0], STDIN_FILENO);
      if (argc > 2)
      {
         dup2(fds2[1], STDOUT_FILENO); /* Second pipe */
      }

      close(fds[0]);
      close(fds[1]);
      close(fds2[0]);
      close(fds2[1]);
      close(fds3[0]);
      close(fds3[1]);

      if (execvp(argv2[0], argv2) < 0)
      return -1;
   }

   if ((pid3 = fork()) == 0)
   {
      dup2(fds2[0], STDIN_FILENO);
      if (argc > 3)
      {
         dup2(fds3[1], STDOUT_FILENO); /* Third pipe */
      }

      close(fds[0]);
      close(fds[1]);
      close(fds2[0]);
      close(fds2[1]);
      close(fds3[0]);
      close(fds3[1]);

      if (execvp(argv3[0], argv3) < 0)
      return -1;
   }

   if ((pid4 = fork()) == 0)
   {
      dup2(fds3[0], STDIN_FILENO);

      close(fds[0]);
      close(fds[1]);
      close(fds2[0]);
      close(fds2[1]);
      close(fds3[0]);
      close(fds3[1]);

      if (execvp(argv4[0], argv4) < 0)
      return -1;
   }

   close(fds[0]);
   close(fds[1]);
   close(fds2[0]);
   close(fds2[1]);
   close(fds3[0]);
   close(fds3[1]);

   waitpid(pid1, NULL, 0); /* wait for child to finish before exiting*/ /* Line 220 - 223 generated by ChatGPT */
   waitpid(pid2, NULL, 0);
   waitpid(pid3, NULL, 0);
   waitpid(pid4, NULL, 0);

   return 0;
}